`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: NUS
// Engineer: Shahzor Ahmad, Rajesh C Panicker
// 
// Create Date: 27.09.2016 10:59:44
// Design Name: 
// Module Name: MCycle
// Project Name: 
// Target Devices: 
// Tool Versions: 
// Description: 
// 
// Dependencies: 
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
// 
//////////////////////////////////////////////////////////////////////////////////
/* 
----------------------------------------------------------------------------------
--	(c) Shahzor Ahmad, Rajesh C Panicker
--	License terms :
--	You are free to use this code as long as you
--		(i) DO NOT post it on any public repository;
--		(ii) use it only for educational purposes;
--		(iii) accept that the program is provided "as is" without warranty of any kind or assurance regarding its suitability for any particular purpose;
--		(iv) send an email to rajesh.panicker@ieee.org briefly mentioning its use (except when used for the course CG3207 at the National University of Singapore);
--		(v) retain this notice in this file or any files derived from this.
----------------------------------------------------------------------------------
*/

module MCycle

    #(parameter width = 4) // Keep this at 4 to verify your algorithms with 4 bit numbers (easier). When using MCycle as a component in RV, generic map it to 32.
    (
        input CLK,
        input RESET, // Connect this to the reset of the RV processor.
        input Start, // Multi-cycle Enable. The control unit should assert this when an instruction with a multi-cycle operation is detected.
        input [1:0] MCycleOp, // Multi-cycle Operation. "00" for signed multiplication, "01" for unsigned multiplication, "10" for signed division, "11" for unsigned division. Generated by Control unit
        input [width-1:0] Operand1, // Multiplicand / Dividend
        input [width-1:0] Operand2, // Multiplier / Divisor
        output reg [width-1:0] Result1, // LSW of Product / Quotient
        output reg [width-1:0] Result2, // MSW of Product / Remainder
        output reg Busy // Set immediately when Start is set. Cleared when the Results become ready. This bit can be used to stall the processor while multi-cycle operations are on.
    );
    
// use the Busy signal to reset WE_PC to 0 in RV.v (aka "freeze" PC). The two signals are complements of each other
// since the IDLE_PROCESS is combinational, instantaneously asserts Busy once Start is asserted
  
    localparam IDLE = 1'b0 ;
    localparam COMPUTING = 1'b1 ;
    reg state = IDLE ;
    reg n_state = IDLE ;
   
    reg done ;
    reg [7:0] count = 0 ; // assuming no computation takes more than 256 cycles.
    reg [2*width-1:0] temp_sum = 0 ;
    reg [2*width-1:0] shifted_op1 = 0 ;
    reg [2*width-1:0] shifted_op2 = 0 ;
    wire [7:0] n_count ;
    wire [2*width-1:0] n_temp_sum, n_shifted_op1, n_shifted_op2 ;
    wire n_done ;
   
    always @(*) begin : IDLE_PROCESS
        // Busy is a Mealy output: Start asserts it while the state is IDLE.
        if(~RESET && ((state == IDLE && Start) ||
                      (state == COMPUTING && ~done))) begin
            n_state = COMPUTING ;
            Busy = 1'b1 ;
        end else begin
            n_state = IDLE ;
            Busy = 1'b0 ;
        end
    end


    // Choose the values used at the start of this cycle.
    wire load_operands = RESET || (n_state == COMPUTING && state == IDLE) ;
    wire [7:0] step_count = load_operands ? 8'd0 : count ;
    wire [2*width-1:0] step_sum = load_operands ? {2*width{1'b0}} : temp_sum ;
    wire [2*width-1:0] step_op1 = load_operands ?
        {{width{~MCycleOp[0] & Operand1[width-1]}}, Operand1} : shifted_op1 ;
    wire [2*width-1:0] step_op2 = load_operands ?
        {{width{~MCycleOp[0] & Operand2[width-1]}}, Operand2} : shifted_op2 ;

    // One shift-and-add multiplication step.
    wire multiply = ~MCycleOp[1] ;
    wire [2*width-1:0] sum_after_add = step_op2[0] ?
        step_sum + step_op1 : step_sum ;
    wire [2*width-1:0] op1_after_shift = {step_op1[2*width-2:0], 1'b0} ;
    wire [2*width-1:0] op2_after_shift = {1'b0, step_op2[2*width-1:1]} ;
    // Signed multiplication takes 2*width cycles; unsigned takes width.
    wire multiply_done = (MCycleOp[0] && step_count == width-1) ||
                         (~MCycleOp[0] && step_count == 2*width-1) ;

    // TODO (students): replace the one-cycle division placeholder.
    // It currently returns Operand1 in Result2 and Operand2 in Result1.
    assign n_count = multiply ? step_count + 1'b1 : step_count ;
    assign n_temp_sum = multiply ? sum_after_add : {Operand1, Operand2} ;
    assign n_shifted_op1 = multiply ? op1_after_shift : step_op1 ;
    assign n_shifted_op2 = multiply ? op2_after_shift : step_op2 ;
    assign n_done = multiply ? multiply_done : 1'b1 ;

    always @(posedge CLK) begin : REGISTER_PROCESS
        state <= n_state ;
        count <= n_count ;
        temp_sum <= n_temp_sum ;
        shifted_op1 <= n_shifted_op1 ;
        shifted_op2 <= n_shifted_op2 ;
        done <= n_done ;
        Result2 <= n_temp_sum[2*width-1 : width] ;
        Result1 <= n_temp_sum[width-1 : 0] ;
    end
   
endmodule








